Axpd-7405: Add Support for Schema Version Resource CRD
Axual/terraform-provider-axual pull request #24
Opened 2023-08-31 16:27 UTC by danny-akp

- Schema version is a resource that supports CREAT, READ and DELETE

2023-09-04 13:10 UTC, kasparAxual approved these changes

2023-09-04 13:10 UTC, kasparAxual commented on axual-webclient/client.go
> +	log.Println("Logging")
Please remove this

2023-09-04 14:45 UTC, markaxual requested changes

2023-09-04 14:45 UTC, markaxual commented on CHANGELOG.md
> +* Support Managing Schema Version
Maybe we can say Support Managing Avro Schemas

2023-09-04 14:45 UTC, markaxual commented on axual-webclient/schema_version_data.go
> +package webclient
Let's keep formatting similar to existing files. Your spacing is inconsistent

2023-09-04 14:45 UTC, markaxual commented on internal/provider/provider.go
> +		"axual_schema_version": schemaVersionResourceType{},
Fix Formatting

2023-09-04 14:45 UTC, markaxual commented on internal/provider/resource_schema_version.go
> +			"schema_version_id": {
Can we keep this as id. I would prefer it this way as it's consistent with all our other resources.

2023-09-05 06:23 UTC, markaxual approved these changes

2023-09-05 07:49 UTC, yunusaxual approved these changes

2023-09-05 07:51 UTC, merged