Axpd-7704: Support Data Sources
Axual/terraform-provider-axual pull request #28
Opened 2023-09-20 14:42 UTC by danny-akp

We are supporting data sources for the following resources:

- axual_group
- axual_environment
- axual_topic
- axual_application
- axual_application_access_grant

A documentiation on how to use is also provided in `guides/dato-sources.md`

2023-09-28 11:36 UTC, markaxual requested changes
Nice work. Some comments

2023-09-28 11:36 UTC, markaxual commented on axual-webclient/application_access_grant.go
> +	values.Add("accessType", data.AccessType)
This function should be generic enough to handle all valid scenarios of `GetApplicationAccessGrantsByAttributes` so all these attributes must be optional, and all the other possible attributes should be possible.

2023-09-28 11:36 UTC, markaxual commented on axual-webclient/environment.go
> +	o := EnvironmentByNameResponse{}
Why are we changing the response here?

2023-09-28 11:36 UTC, markaxual commented on axual-webclient/groups_data.go
> +type GroupByNameResponse struct {
Group what by name? It's a bit ambiguous. Maybe `GetGroupsByNameResponse`

2023-09-28 12:31 UTC, markaxual commented
@danny-akp Please update the Changelog

2023-09-29 05:45 UTC, markaxual approved these changes

2023-10-02 10:49 UTC, yunusaxual approved these changes
We tested. It works great.

2023-10-02 11:05 UTC, merged