Add instance as data source
Axual/terraform-provider-axual pull request #48
Opened 2024-11-13 15:48 UTC by bhuvaneswaribalaji07

Changes to Add instance as data-source

2024-11-15 13:24 UTC, kasparAxual requested changes

2024-11-15 13:33 UTC, kasparAxual requested changes

2024-11-15 13:33 UTC, kasparAxual commented on templates/data-sources/instance.md.tmpl
> +- name - (Required) The group name.
instance?

2024-11-15 13:33 UTC, kasparAxual commented on templates/data-sources/instance.md.tmpl
> +- description The group description.
instance?

2024-11-15 13:33 UTC, kasparAxual commented on templates/data-sources/instance.md.tmpl
> +- id group unique identifier.
instance?

2024-11-15 13:33 UTC, kasparAxual commented on templates/guides/data-sources.md
> +- To define a `axual_group` data source, provide the group name:
instance?

2024-11-15 13:33 UTC, kasparAxual commented on docs/data-sources/instance.md
> +- name - (Required) The group name.
instance?

2024-11-15 13:33 UTC, kasparAxual commented on docs/data-sources/instance.md
> +- description The group description.
instance?

2024-11-15 13:33 UTC, kasparAxual commented on internal/provider/data_source_instance.go
> +					stringvalidator.LengthBetween(3, 80),
Why 80? In Api max is 50.

2024-11-15 13:33 UTC, kasparAxual commented on internal/provider/data_source_instance.go
> +					stringvalidator.RegexMatches(regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9 ._-]*$`), "can only contain letters, numbers, dots, spaces, dashes and underscores, but cannot begin with an underscore, d
The API Java regex allows the string to start with a separator (dot, dash, underscore, or space).
The Terraform Go regex requires the string to start with an alphanumeric character (A-Za-z0-9).
Please change Terraform regex to match API Java regex.

2024-11-15 13:33 UTC, kasparAxual commented on internal/provider/data_source_instance.go
> +
Please add a test what happens if the instance is not found

2024-11-15 13:33 UTC, kasparAxual commented on internal/provider/data_source_group.go
> +	if len(groupByName.Embedded.Groups) == 0 {
Please add a test what happens if the group is not found

2024-11-15 13:33 UTC, kasparAxual commented on internal/provider/data_source_topic.go
> +	if len(topicByName.Embedded.Topics) == 0 {
Please add a test what happens if the topic is not found

2024-11-15 13:33 UTC, kasparAxual commented on internal/provider/data_source_environment.go
> +	if len(environmentByName.Embedded.Environments) == 0 {
Please add a test what happens if the env is not found

2024-11-18 15:12 UTC, tunji-axual commented on internal/provider/data_source_instance.go
> +		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read instance, got error: %s", err2))
```suggestion
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read instance with ID '%s', got error: %s", instanceByName.Uid, err2))
```

2024-11-18 15:12 UTC, tunji-axual commented on internal/tests/InstanceDataSource/instance_data_source_test.go
> +			},
Can we add a test case for invalid name 

```suggestion
			},
			{
				// Invalid name attribute
				Config:      GetProvider() + GetFile("axual_instance_invalid_name.tf"),
				ExpectError: regexp.MustCompile("Invalid attribute value: The name must be between 3 and 50 characters."),
			},
```

2024-11-20 05:51 UTC, tunji-axual approved these changes

2024-11-25 12:09 UTC, danny-akp approved these changes

2024-11-25 12:22 UTC, merged